const mongoose = require('mongoose');

const ticketSchema = new mongoose.Schema({
    event: { 
        type: mongoose.Schema.Types.ObjectId, 
        ref: 'Event', 
        required: true 
    },
    user: { 
        type: mongoose.Schema.Types.ObjectId, 
        ref: 'User', 
        required: true 
    },
    purchasePrice: { 
        type: Number, 
        required: true 
    },
    qrCode: { 
        type: String // Stores Base64 string generated by the controller
    },
    status: { 
        type: String, 
        enum: ['Valid', 'Used', 'Cancelled'], 
        default: 'Valid' 
    },
    // --- NEW FIELD: Tracking Entry Time ---
    scannedAt: {
        type: Date,
        default: null
    }
}, { timestamps: true });

module.exports = mongoose.model('Ticket', ticketSchema);